version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu
#init:
#  - git config --global core.autocrlf true
configuration: Release
test: off
environment:
  assembly_version: value

for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh build.sh

-
  matrix:
    only:
      - image: Visual Studio 2019
  build_script:
    - ps: ./Build.ps1
  artifacts:
  - path: artifacts/GoogleTranslateApi.*.nupkg
  deploy:
  - provider: NuGet
    api_key:
      secure: j45j302qWyN118IC53/Td8YjEkpmxcb3iSpZT67tlyT/SSb4GIVDRZ1Wak6Qiddy
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: SJhGDlty7WNVlwbZUrcn7YGjQdvkcEDqbXcqpBYPLb1iS1gaOhQSHhzeUZKJ/wJz
    artifacts:
      /GoogleTranslateApi.*\.nupkg/
    tag: v$(assembly_version)
    on:
      branch: master
